[package]
name = "stickerbox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
floem = { version = "0.2.0", features = ["serde", "image-gif", "image-avif", "image-bmp"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
