import { SettingsWindow } from "./settings/main.slint";
import { SearchWindow } from "./search/main.slint";

export component SearchWindow inherits Window {
	title: "Stickerbox Search";
	default-font-size: 18px;
	preferred-width: 500px;
	preferred-height: 400px;
	// no-frame: true;
	SearchWindow {}
}

export component SettingsWindow inherits Window {
	title: "Stickerbox Settings";
	preferred-width: 800px;
	preferred-height: 600px;
	default-font-size: 18px;
	callback show-secondary-window();
	SettingsWindow {}
}
