import { Slider, HorizontalBox, VerticalBox, GroupBox, ComboBox, ScrollView } from "std-widgets.slint";
import { ThemedButton } from "themed-button.slint";

export component MainWindow inherits Window {
    title: "Test";
    preferred-width: 800px;
    preferred-height: 600px;
	background: red;

	callback click_button_cb <=> png_btn.png_button_pointer_event;
	in property <bool> btn_clicked: false;

	in property <[image]> images;
	in property <length> scroll_height;

    HorizontalBox {
		padding: 0px;
		spacing: 0px;

		Rectangle {
			border-radius: 1px;
			width: 50%;
			background: blue;
			png_btn := ThemedButton {
				btn_clicked <=> btn_clicked;
			}
		}

		Rectangle {
			width: 50%;
			background: green;
			border-width: 1px;
			border-color: red;

			ScrollView {
				viewport-height: scroll_height;

				VerticalLayout {
					spacing: 8px;
					height: 100%;
					for image in images : Image {
						source: image;
						height: 128px;
						width: 128px;
					}
				}
			}
		}
    }
}
