import { SearchTabButton } from "tab.slint";
import { HorizontalBox } from "std-widgets.slint";

export enum SearchTab {
	Sticker,
	Compose,
	FunText,
	GifSearch,
}

export component SearchTabBar {
	in-out property <SearchTab> selected_tab: SearchTab.Sticker;

	height: 10%;

	HorizontalBox {
		padding: 0px;
		spacing: 0px;

		SearchTabButton {
			text: "Sticker";
			clicked => { selected_tab = SearchTab.Sticker; }
		}
		SearchTabButton {
			text: "TODO: Compose";
			clicked => { selected_tab = SearchTab.Compose; }
		}
		SearchTabButton {
			text: "TODO: Fun Text Type";
			clicked => { selected_tab = SearchTab.FunText; }
		}
		SearchTabButton {
			text: "TODO: Gif Search";
			clicked => { selected_tab = SearchTab.GifSearch; }
		}
	}
}
