import { HorizontalBox } from "std-widgets.slint";
import { Button } from "std-widgets.slint";

export enum SearchTab {
	Sticker,
	Compose,
	FunText,
	GifSearch,
}

component SearchTabButton {
	in-out property <string> text;
	callback clicked;
	in-out property enabled <=> btn.enabled;

	btn:= Button {
		horizontal-stretch: 1;
		text <=> text;
		width: 100%;
		height: 100%;
		clicked => { clicked (); }
		// background: purple;
		// border-width: 1px;
		// border-color: black;

		// TouchArea {
			// width: 100%;
			// height: 100%;
			// Text { text <=> text; }
			// clicked => { tab_clicked() }
		// }
	}
}

export component SearchTabBar {
	in-out property <SearchTab> selected_tab: SearchTab.Sticker;

	height: 10%;

	HorizontalBox {
		padding: 0px;
		spacing: 0px;

		SearchTabButton {
			text: "Sticker";
			enabled: selected_tab != SearchTab.Sticker;
			clicked => { selected_tab = SearchTab.Sticker; }
		}
		SearchTabButton {
			text: "TODO: Compose";
			enabled: selected_tab != SearchTab.Compose;
			clicked => { selected_tab = SearchTab.Compose; }
		}
		SearchTabButton {
			text: "TODO: Fun Text Type";
			enabled: selected_tab != SearchTab.FunText;
			clicked => { selected_tab = SearchTab.FunText; }
		}
		SearchTabButton {
			text: "TODO: Gif Search";
			enabled: selected_tab != SearchTab.GifSearch;
			clicked => { selected_tab = SearchTab.GifSearch; }
		}
	}
}
